project:
  type: website

website:
  title: "EF2023 Dashboard Website"
  search: true
  reader-mode: true

  navbar:
    background: "#135"
    foreground: "white"
    left:
      - href: index.qmd
        text: "Home"
      - href: dashboard-1.qmd
        text: "Dashboard"
      - href: about.qmd
        text: "About"
    tools:
      - icon: "github"
        href: ""

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

  dashboard:
    mainfont: "Source Sans Pro, BC Sans, Noto Sans, Onest, Verdana, Arial, sans-serif"
    theme:
      - cosmo
      - brand
    css: styles_dashboard.css

editor: source
