---
title: "Dashboard"
format:
  dashboard:
    expandable: false
---

```{r}
#| message: false
#| warning: false
#| include: false

# install.packages("D:/MDi/Documents/R/package20260206", repos = NULL, type = "source")
# install.packages("tidyverse")
# install.packages("forcats")
# install.packages("bslib")
# install.packages("bsicons")

library(package20260206)
library(tidyverse)
library(plotly)
library(forcats)
library(bslib)
library(bsicons)
library(htmltools)
```

# Production

## _ {.tabset}

### Oil {.tabset}

#### Total

```{r}
#| include: false
Oil_Total <- EF2023$crude_oil_production %>%
  filter(Unit == "Thousand Cubic Metres per day",
         Variable == "Total") %>%
  mutate(Region = Region %>% factor %>% fct_recode(
    "AB" = "Alberta", "BC" = "British Columbia", "MB" = "Manitoba",
    "NB" = "New Brunswick", "NL" = "Newfoundland and Labrador",
    "NS" = "Nova Scotia", "NT" = "Northwest Territories",
    "NU" = "Nunavut", "ON" = "Ontario", "PE" = "Prince Edward Island",
    "QC" = "Quebec", "SK" = "Saskatchewan", "YT" = "Yukon",
    "Canada" = "Canada") %>% fct_relevel("Canada", after = 0),
    Scenario = Scenario %>% fct_relevel("Current Measures", after = 0))
```

::: {style="display: grid; grid-template-columns: 1fr 3fr; gap: 1rem;"}

:::: {style="display: grid; grid-template-rows: 1fr 1fr 1fr 1.5fr; gap: 1rem;"}

```{r}
### Card: Current Measures total (1/3)
v1 <- Oil_Total %>%
  filter(Year > 2022,
         Region == "Canada",
         Scenario == "Current Measures") %>%
  pull(Value) %>%
  {sum(. * 1000) * 365.24}

value_box_value <- v1 %>%
  rp_format_proper2(format = list(do_B = T)) %>% 
  paste0(" m³")

value_box(theme = value_box_theme(bg = "#777", fg = "#EEE"),
        title = "Total (2023+)",
        value = value_box_value,
        tag("p", "Current measures (baseline)"))
###
```

```{r}
### Card: Canada Net-zero total (2/3)
v2 <- Oil_Total %>%
  filter(Year > 2022,
         Region == "Canada",
         Scenario == "Canada Net-zero") %>%
  pull(Value) %>%
  {sum(. * 1000) * 365.24}

value_box_value <- v2 %>%
  rp_format_proper2(format = list(do_B = T)) %>% 
  paste0(" m³")

value_box(theme = value_box_theme(bg = "#7e4343", fg = "#EEE"),
        title = "Total (2023+)",
        value = value_box_value,
        tag("p", paste0("Canada Net-zero", " (", round((v2/v1 - 1) * 100), "%)")))
###
```

```{r}
### Card: Global Net-zero total (3/3)
v3 <- Oil_Total %>%
  filter(Year > 2022,
         Region == "Canada",
         Scenario == "Global Net-zero") %>%
  pull(Value) %>%
  {sum(. * 1000) * 365.24}

value_box_value <- v3 %>%
  rp_format_proper2(format = list(do_B = T)) %>% 
  paste0(" m³")

value_box(theme = value_box_theme(bg = "#416070", fg = "#EEE"),
        title = "Total (2023+)",
        value = value_box_value,
        tag("p", paste0("Global Net-zero", " (", round((v3/v1 - 1) * 100), "%)")))
###
```

```{r}
### Card: Top contributor (Region)
# Get top contributor (Region)
value_box_data <- Oil_Total %>%
  filter(Region != "Canada") %>%
  # Compute averages and contributions
  summarize(Value_Total = mean(Value),
            Value_Average = mean(Value),
            .by = Region) %>%
  mutate(Value_Percentage = Value_Total / sum(Value_Total)) %>% 
  # Get highest contribution
  arrange(desc(Value_Percentage)) %>%
  head(1) %>% 
  # Prepare labels
  mutate(Line_1 = paste0("Averaging ", round(Value_Average, 1), "k m³/day"),
         Line_2 = paste0("Contributing ", round(100 * Value_Percentage, 0), "% (avg.)"))
value_box_value <- value_box_data$Region
value_box_tag_1 <- value_box_data$Line_1
value_box_tag_2 <- value_box_data$Line_2

# Prepare showcase plot
value_box_plot <- Oil_Total %>% 
  filter(Region == value_box_data$Region) %>%
  ggplot(aes(x = Year, y = Value, group = Scenario,
             col = Scenario, fill = Scenario,
             ymin = pmin(0, Value), ymax = pmax(0, Value))) +
  geom_ribbon(col = NULL, fill = "#AAA", alpha = 0.1) +
  geom_line(aes(text = paste0(round(Value), ": ", Scenario, " (", Year, ")")),
            alpha = 0.25, lwd = 0.25) +
  scale_color_discrete(palette = c("#777", "#7e4343", "#416070")) +
  theme_void() +
  theme(legend.position = "none")
value_box_plot <- ggplotly(value_box_plot, tooltip = "text") %>%
  layout(plot_bgcolor = "rgba(1,1,1,0)", hovermode = "x",
         hoverlabel = list(font = list(family = "Onest", size = 13))) %>%
  config(displayModeBar = F)

# Draw value box
value_box(theme = value_box_theme(bg = "#EEE", fg = "#777"),
        title = "Top contributor",
        showcase = value_box_plot,
        showcase_layout = "bottom",
        value = value_box_value,
        # tag("p", value_box_tag_1),
        tag("p", value_box_tag_2))
###

```

::::

:::: {style="display: grid;"}

```{r}
# Main plot
Oil_Total %>%
  ridge_facet_plot(rp_X = Year, rp_Y = Value, rp_F1 = Scenario, rp_F2 = Region,
                   rp_title_main = "Canadian Oil Production",
                   rp_title_Y = "Production", rp_unit_abbrev = "k m³/day",
                   rp_labs_Y = list(digits = 0, do_k = F, do_e = F),
                   rp_alpha = list(ribbons = 0.35))
```

::::

:::

#### Upgraded Bitumen

```{r}
#| include: false
Oil_Total <- EF2023$crude_oil_production %>%
  filter(Unit == "Thousand Cubic Metres per day",
         Variable == "(Upgraded Bitumen)") %>%
  mutate(Region = Region %>% factor %>% fct_recode(
    "AB" = "Alberta", "BC" = "British Columbia", "MB" = "Manitoba",
    "NB" = "New Brunswick", "NL" = "Newfoundland and Labrador",
    "NS" = "Nova Scotia", "NT" = "Northwest Territories",
    "NU" = "Nunavut", "ON" = "Ontario", "PE" = "Prince Edward Island",
    "QC" = "Quebec", "SK" = "Saskatchewan", "YT" = "Yukon",
    "Canada" = "Canada") %>% fct_relevel("Canada", after = 0),
    Scenario = Scenario %>% fct_relevel("Current Measures", after = 0))
```

::: {style="display: grid; grid-template-columns: 1fr 3fr; gap: 1rem;"}

:::: {style="display: grid; grid-template-rows: 1fr 1fr 1fr 1.5fr; gap: 1rem;"}

```{r}
### Card: Current Measures total (1/3)
v1 <- Oil_Total %>%
  filter(Year > 2022,
         Region == "Canada",
         Scenario == "Current Measures") %>%
  pull(Value) %>%
  {sum(. * 1000) * 365.24}

value_box_value <- v1 %>%
  rp_format_proper2(format = list(do_B = T)) %>% 
  paste0(" m³")

value_box(theme = value_box_theme(bg = "#777", fg = "#EEE"),
        title = "Total (2023+)",
        value = value_box_value,
        tag("p", "Current measures (baseline)"))
###
```

```{r}
### Card: Canada Net-zero total (2/3)
v2 <- Oil_Total %>%
  filter(Year > 2022,
         Region == "Canada",
         Scenario == "Canada Net-zero") %>%
  pull(Value) %>%
  {sum(. * 1000) * 365.24}

value_box_value <- v2 %>%
  rp_format_proper2(format = list(do_B = T)) %>% 
  paste0(" m³")

value_box(theme = value_box_theme(bg = "#7e4343", fg = "#EEE"),
        title = "Total (2023+)",
        value = value_box_value,
        tag("p", paste0("Canada Net-zero", " (", round((v2/v1 - 1) * 100), "%)")))
###
```

```{r}
### Card: Global Net-zero total (3/3)
v3 <- Oil_Total %>%
  filter(Year > 2022,
         Region == "Canada",
         Scenario == "Global Net-zero") %>%
  pull(Value) %>%
  {sum(. * 1000) * 365.24}

value_box_value <- v3 %>%
  rp_format_proper2(format = list(do_B = T)) %>% 
  paste0(" m³")

value_box(theme = value_box_theme(bg = "#416070", fg = "#EEE"),
        title = "Total (2023+)",
        value = value_box_value,
        tag("p", paste0("Global Net-zero", " (", round((v3/v1 - 1) * 100), "%)")))
###
```

```{r}
### Card: Top contributor (Region)
# Get top contributor (Region)
value_box_data <- Oil_Total %>%
  filter(Region != "Canada") %>%
  # Compute averages and contributions
  summarize(Value_Total = mean(Value),
            Value_Average = mean(Value),
            .by = Region) %>%
  mutate(Value_Percentage = Value_Total / sum(Value_Total)) %>% 
  # Get highest contribution
  arrange(desc(Value_Percentage)) %>%
  head(1) %>% 
  # Prepare labels
  mutate(Line_1 = paste0("Averaging ", round(Value_Average, 1), "k m³/day"),
         Line_2 = paste0("Contributing ", round(100 * Value_Percentage, 0), "% (avg.)"))
value_box_value <- value_box_data$Region
value_box_tag_1 <- value_box_data$Line_1
value_box_tag_2 <- value_box_data$Line_2

# Prepare showcase plot
value_box_plot <- Oil_Total %>% 
  filter(Region == value_box_data$Region) %>%
  ggplot(aes(x = Year, y = Value, group = Scenario,
             col = Scenario, fill = Scenario,
             ymin = pmin(0, Value), ymax = pmax(0, Value))) +
  geom_ribbon(col = NULL, fill = "#AAA", alpha = 0.1) +
  geom_line(aes(text = paste0(round(Value), ": ", Scenario, " (", Year, ")")),
            alpha = 0.25, lwd = 0.25) +
  scale_color_discrete(palette = c("#777", "#7e4343", "#416070")) +
  theme_void() +
  theme(legend.position = "none")
value_box_plot <- ggplotly(value_box_plot, tooltip = "text") %>%
  layout(plot_bgcolor = "rgba(1,1,1,0)", hovermode = "x",
         hoverlabel = list(font = list(family = "Onest", size = 13))) %>%
  config(displayModeBar = F)

# Draw value box
value_box(theme = value_box_theme(bg = "#EEE", fg = "#777"),
        title = "Top contributor",
        showcase = value_box_plot,
        showcase_layout = "bottom",
        value = value_box_value,
        # tag("p", value_box_tag_1),
        tag("p", value_box_tag_2))
###

```

::::

:::: {style="display: grid;"}

```{r}
# Main plot
Oil_Total %>%
  ridge_facet_plot(rp_X = Year, rp_Y = Value, rp_F1 = Scenario, rp_F2 = Region,
                   rp_title_main = "Canadian Oil Production",
                   rp_title_Y = "Production", rp_unit_abbrev = "k m³/day",
                   rp_labs_Y = list(digits = 0, do_k = F, do_e = F),
                   rp_alpha = list(ribbons = 0.35))
```

::::

:::

#### C5+

```{r}
# EF2023$crude_oil_production %>%
#   filter(Unit == "Thousand Cubic Metres per day",
#          Variable == "C5+") %>%
#   mutate(Region = Region %>% factor %>% fct_recode(
#     "AB" = "Alberta", "BC" = "British Columbia", "MN" = "Manitoba",
#     "NB" = "New Brunswick", "NL" = "Newfoundland and Labrador",
#     "NS" = "Nova Scotia", "NT" = "Northwest Territories",
#     "NV" = "Nunavut", "ON" = "Ontario", "PEI" = "Prince Edward Island",
#     "QC" = "Quebec", "SK" = "Saskatchewan", "YK" = "Yukon",
#     "Canada" = "Canada") %>% fct_relevel("Canada", after = 0)) %>%
#   ridge_facet_plot(rp_X = Year,
#                    rp_Y = Value,
#                    rp_F1 = Scenario,
#                    rp_F2 = Region,
#                    rp_alpha = list(ribbons = 0.35),
#                    rp_title_main = "Canadian C5+ Production",
#                    rp_title_Y = "Production",
#                    rp_unit_abbrev = "k m³/day")
```

#### Conventional Heavy

```{r}
# EF2023$crude_oil_production %>%
#   filter(Unit == "Thousand Cubic Metres per day",
#          Variable == "Conventional Heavy") %>%
#   mutate(Region = Region %>% factor %>% fct_recode(
#     "AB" = "Alberta", "BC" = "British Columbia", "MN" = "Manitoba",
#     "NB" = "New Brunswick", "NL" = "Newfoundland and Labrador",
#     "NS" = "Nova Scotia", "NT" = "Northwest Territories",
#     "NV" = "Nunavut", "ON" = "Ontario", "PEI" = "Prince Edward Island",
#     "QC" = "Quebec", "SK" = "Saskatchewan", "YK" = "Yukon",
#     "Canada" = "Canada") %>% fct_relevel("Canada", after = 0)) %>%
#   ridge_facet_plot(rp_X = Year,
#                    rp_Y = Value,
#                    rp_F1 = Scenario,
#                    rp_F2 = Region,
#                    rp_alpha = list(ribbons = 0.35),
#                    rp_title_main = "Canadian Conventional Heavy Production",
#                    rp_title_Y = "Production",
#                    rp_unit_abbrev = "k m³/day")
```

#### Conventional Light

```{r}
# EF2023$crude_oil_production %>%
#   filter(Unit == "Thousand Cubic Metres per day",
#          Variable == "Conventional Light") %>%
#   mutate(Region = Region %>% factor %>% fct_recode(
#     "AB" = "Alberta", "BC" = "British Columbia", "MN" = "Manitoba",
#     "NB" = "New Brunswick", "NL" = "Newfoundland and Labrador",
#     "NS" = "Nova Scotia", "NT" = "Northwest Territories",
#     "NV" = "Nunavut", "ON" = "Ontario", "PEI" = "Prince Edward Island",
#     "QC" = "Quebec", "SK" = "Saskatchewan", "YK" = "Yukon",
#     "Canada" = "Canada") %>% fct_relevel("Canada", after = 0)) %>%
#   ridge_facet_plot(rp_X = Year,
#                    rp_Y = Value,
#                    rp_F1 = Scenario,
#                    rp_F2 = Region,
#                    rp_alpha = list(ribbons = 0.35),
#                    rp_title_main = "Canadian Conventional Light Production",
#                    rp_title_Y = "Production",
#                    rp_unit_abbrev = "k m³/day")
```

#### Field Condensate

```{r}
# EF2023$crude_oil_production %>%
#   filter(Unit == "Thousand Cubic Metres per day",
#          Variable == "Field Condensate") %>%
#   mutate(Region = Region %>% factor %>% fct_recode(
#     "AB" = "Alberta", "BC" = "British Columbia", "MN" = "Manitoba",
#     "NB" = "New Brunswick", "NL" = "Newfoundland and Labrador",
#     "NS" = "Nova Scotia", "NT" = "Northwest Territories",
#     "NV" = "Nunavut", "ON" = "Ontario", "PEI" = "Prince Edward Island",
#     "QC" = "Quebec", "SK" = "Saskatchewan", "YK" = "Yukon",
#     "Canada" = "Canada") %>% fct_relevel("Canada", after = 0)) %>%
#   ridge_facet_plot(rp_X = Year,
#                    rp_Y = Value,
#                    rp_F1 = Scenario,
#                    rp_F2 = Region,
#                    rp_alpha = list(ribbons = 0.35),
#                    rp_title_main = "Canadian Field Condensate Production",
#                    rp_title_Y = "Production",
#                    rp_unit_abbrev = "k m³/day")
```

#### In Situ Bitumen

```{r}
# EF2023$crude_oil_production %>%
#   filter(Unit == "Thousand Cubic Metres per day",
#          Variable == "In Situ Bitumen") %>%
#   mutate(Region = Region %>% factor %>% fct_recode(
#     "AB" = "Alberta", "BC" = "British Columbia", "MN" = "Manitoba",
#     "NB" = "New Brunswick", "NL" = "Newfoundland and Labrador",
#     "NS" = "Nova Scotia", "NT" = "Northwest Territories",
#     "NV" = "Nunavut", "ON" = "Ontario", "PEI" = "Prince Edward Island",
#     "QC" = "Quebec", "SK" = "Saskatchewan", "YK" = "Yukon",
#     "Canada" = "Canada") %>% fct_relevel("Canada", after = 0)) %>%
#   ridge_facet_plot(rp_X = Year,
#                    rp_Y = Value,
#                    rp_F1 = Scenario,
#                    rp_F2 = Region,
#                    rp_alpha = list(ribbons = 0.35),
#                    rp_title_main = "Canadian In Situ Bitumen Production",
#                    rp_title_Y = "Production",
#                    rp_unit_abbrev = "k m³/day")
```

#### Mined Bitumen

```{r}
# EF2023$crude_oil_production %>%
#   filter(Unit == "Thousand Cubic Metres per day",
#          Variable == "Mined Bitumen") %>%
#   mutate(Region = Region %>% factor %>% fct_recode(
#     "AB" = "Alberta", "BC" = "British Columbia", "MN" = "Manitoba",
#     "NB" = "New Brunswick", "NL" = "Newfoundland and Labrador",
#     "NS" = "Nova Scotia", "NT" = "Northwest Territories",
#     "NV" = "Nunavut", "ON" = "Ontario", "PEI" = "Prince Edward Island",
#     "QC" = "Quebec", "SK" = "Saskatchewan", "YK" = "Yukon",
#     "Canada" = "Canada") %>% fct_relevel("Canada", after = 0)) %>%
#   ridge_facet_plot(rp_X = Year,
#                    rp_Y = Value,
#                    rp_F1 = Scenario,
#                    rp_F2 = Region,
#                    rp_alpha = list(ribbons = 0.35),
#                    rp_title_main = "Canadian Mined Bitumen Production",
#                    rp_title_Y = "Production",
#                    rp_unit_abbrev = "k m³/day")
```

### Hydrogen {.tabset}

#### Biomass

```{r}
# EF2023$hydrogen_production %>%
#   filter(Variable == "Biomass") %>%
#   mutate(Region = Region %>% factor %>% fct_recode(
#     "AB" = "Alberta", "BC" = "British Columbia", "MN" = "Manitoba",
#     "NB" = "New Brunswick", "NL" = "Newfoundland and Labrador",
#     "NS" = "Nova Scotia", "NT" = "Northwest Territories",
#     "NV" = "Nunavut", "ON" = "Ontario", "PEI" = "Prince Edward Island",
#     "QC" = "Quebec", "SK" = "Saskatchewan", "YK" = "Yukon",
#     "Canada" = "Canada") %>% fct_relevel("Canada", after = 0)) %>%
#   ridge_facet_plot(rp_X = Year,
#                    rp_Y = Value,
#                    rp_F1 = Scenario,
#                    rp_F2 = Region,
#                    rp_alpha = list(ribbons = 0.35),
#                    rp_title_main = "Canadian Hydrogen Production (Biomass)",
#                    rp_title_Y = "Production",
#                    rp_unit_abbrev = "Mt")
```

```{r}
#| include: false
Hydrogen_Biomass <- EF2023$hydrogen_production %>%
  filter(Unit == "Megatonnes",
         Variable == "Biomass") %>%
  mutate(Region = Region %>% factor %>% fct_recode(
    "AB" = "Alberta", "BC" = "British Columbia", "MB" = "Manitoba",
    "NB" = "New Brunswick", "NL" = "Newfoundland and Labrador",
    "NS" = "Nova Scotia", "NT" = "Northwest Territories",
    "NU" = "Nunavut", "ON" = "Ontario", "PE" = "Prince Edward Island",
    "QC" = "Quebec", "SK" = "Saskatchewan", "YT" = "Yukon",
    "Canada" = "Canada") %>% fct_relevel("Canada", after = 0),
    Scenario = Scenario %>% fct_relevel("Current Measures", after = 0))
```

::: {style="display: grid; grid-template-columns: 1fr 3fr; gap: 1rem;"}

:::: {style="display: grid; grid-template-rows: 1fr 1fr 1fr 1.5fr; gap: 1rem;"}

```{r}
### Card: Current Measures total (1/3)
v1 <- Hydrogen_Biomass %>%
  filter(Year > 2022,
         Region == "Canada",
         Scenario == "Current Measures") %>%
  pull(Value) %>%
  {sum(. * 1000000)}

value_box_value <- v1 %>%
  rp_format_proper2(format = list(do_M = T)) %>% 
  paste0(" t")

value_box(theme = value_box_theme(bg = "#777", fg = "#EEE"),
        title = "Total (2023+)",
        value = value_box_value,
        tag("p", "Current measures (baseline)"))
###
```

```{r}
### Card: Canada Net-zero total (2/3)
v2 <- Hydrogen_Biomass %>%
  filter(Year > 2022,
         Region == "Canada",
         Scenario == "Canada Net-zero") %>%
  pull(Value) %>%
  {sum(. * 1000000)}

value_box_value <- v2 %>%
  rp_format_proper2(format = list(do_M = T)) %>% 
  paste0(" t")

value_box(theme = value_box_theme(bg = "#7e4343", fg = "#EEE"),
        title = "Total (2023+)",
        value = value_box_value,
        tag("p", paste0("Canada Net-zero", " (", round((v2/v1 - 1) * 100), "%)")))
###
```

```{r}
### Card: Global Net-zero total (3/3)
v3 <- Hydrogen_Biomass %>%
  filter(Year > 2022,
         Region == "Canada",
         Scenario == "Global Net-zero") %>%
  pull(Value) %>%
  {sum(. * 1000000)}

value_box_value <- v3 %>%
  rp_format_proper2(format = list(do_M = T)) %>% 
  paste0(" t")

value_box(theme = value_box_theme(bg = "#416070", fg = "#EEE"),
        title = "Total (2023+)",
        value = value_box_value,
        tag("p", paste0("Global Net-zero", " (", round((v3/v1 - 1) * 100), "%)")))
###
```

```{r}
### Card: Top contributor (Region)
# Get top contributor (Region)
value_box_data <- Hydrogen_Biomass %>%
  filter(Region != "Canada") %>%
  # Compute averages and contributions
  summarize(Value_Total = mean(Value),
            Value_Average = mean(Value),
            .by = Region) %>%
  mutate(Value_Percentage = Value_Total / sum(Value_Total)) %>% 
  # Get highest contribution
  arrange(desc(Value_Percentage)) %>%
  head(1) %>% 
  # Prepare labels
  mutate(Line_1 = paste0("Averaging ", round(Value_Average, 1), "Mt"),
         Line_2 = paste0("Contributing ", round(100 * Value_Percentage, 0), "% (avg.)"))
value_box_value <- value_box_data$Region
value_box_tag_1 <- value_box_data$Line_1
value_box_tag_2 <- value_box_data$Line_2

# Prepare showcase plot
value_box_plot <- Hydrogen_Biomass %>% 
  filter(Region == value_box_data$Region) %>%
  ggplot(aes(x = Year, y = Value, group = Scenario,
             col = Scenario, fill = Scenario,
             ymin = pmin(0, Value), ymax = pmax(0, Value))) +
  geom_ribbon(col = NULL, fill = "#AAA", alpha = 0.1) +
  geom_line(aes(text = paste0(round(Value, 1), ": ", Scenario, " (", Year, ")")),
            alpha = 0.25, lwd = 0.25) +
  scale_color_discrete(palette = c("#777", "#7e4343", "#416070")) +
  theme_void() +
  theme(legend.position = "none")
value_box_plot <- ggplotly(value_box_plot, tooltip = "text") %>%
  layout(plot_bgcolor = "rgba(1,1,1,0)", hovermode = "x",
         hoverlabel = list(font = list(family = "Onest", size = 13))) %>%
  config(displayModeBar = F)

# Draw value box
value_box(theme = value_box_theme(bg = "#EEE", fg = "#777"),
        title = "Top contributor",
        showcase = value_box_plot,
        showcase_layout = "bottom",
        value = value_box_value,
        # tag("p", value_box_tag_1),
        tag("p", value_box_tag_2))
###

```

::::

:::: {style="display: grid;"}

```{r}
# Main plot
Hydrogen_Biomass %>%
  ridge_facet_plot(rp_X = Year, rp_Y = Value, rp_F1 = Scenario, rp_F2 = Region,
                   rp_title_main = "Canadian Hydrogen Production",
                   rp_title_Y = "Production", rp_unit_abbrev = "Mt",
                   rp_labs_Y = list(digits = 0, do_k = F, do_e = F),
                   rp_alpha = list(ribbons = 0.35))
```

::::

:::

#### Electrolysis

```{r}
# EF2023$hydrogen_production %>%
#   filter(Variable == "Electrolysis") %>%
#   mutate(Region = Region %>% factor %>% fct_recode(
#     "AB" = "Alberta", "BC" = "British Columbia", "MN" = "Manitoba",
#     "NB" = "New Brunswick", "NL" = "Newfoundland and Labrador",
#     "NS" = "Nova Scotia", "NT" = "Northwest Territories",
#     "NV" = "Nunavut", "ON" = "Ontario", "PEI" = "Prince Edward Island",
#     "QC" = "Quebec", "SK" = "Saskatchewan", "YK" = "Yukon",
#     "Canada" = "Canada") %>% fct_relevel("Canada", after = 0)) %>%
#   ridge_facet_plot(rp_X = Year,
#                    rp_Y = Value,
#                    rp_F1 = Scenario,
#                    rp_F2 = Region,
#                    rp_alpha = list(ribbons = 0.35),
#                    rp_title_main = "Canadian Hydrogen Production (Electrolysis)",
#                    rp_title_Y = "Production",
#                    rp_unit_abbrev = "Mt")
```

#### Natural gas with CCS

```{r}
# EF2023$hydrogen_production %>%
#   filter(Variable == "Natural gas with CCS") %>%
#   mutate(Region = Region %>% factor %>% fct_recode(
#     "AB" = "Alberta", "BC" = "British Columbia", "MN" = "Manitoba",
#     "NB" = "New Brunswick", "NL" = "Newfoundland and Labrador",
#     "NS" = "Nova Scotia", "NT" = "Northwest Territories",
#     "NV" = "Nunavut", "ON" = "Ontario", "PEI" = "Prince Edward Island",
#     "QC" = "Quebec", "SK" = "Saskatchewan", "YK" = "Yukon",
#     "Canada" = "Canada") %>% fct_relevel("Canada", after = 0)) %>%
#   ridge_facet_plot(rp_X = Year,
#                    rp_Y = Value,
#                    rp_F1 = Scenario,
#                    rp_F2 = Region,
#                    rp_alpha = list(ribbons = 0.35),
#                    rp_title_main = "Canadian Hydrogen Production (Natural gas with CCS)",
#                    rp_title_Y = "Production",
#                    rp_unit_abbrev = "Mt")
```


# Prices

### Oil Benchmark

```{r}
# EF2023$benchmark_prices %>%
#   filter(Variable %>% str_detect("bbl")) %>%
#   mutate(Variable = Variable %>% str_remove_all(" - 2.*$")) %>%
#   ridge_facet_plot(rp_X = Year, rp_Y = Value, rp_F1 = Variable, rp_F2 = Scenario,
#                    rp_draw = list(ribbons = F, lines = F, smooth = T, medians = F, peaks = F),
#                    rp_alpha = list(se = 0.25, points = 0.25),
#                    rp_title_main = "Oil Benchmark Prices",
#                    rp_unit_abbrev = "2022 US$/bbl")
```
